version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: kneegorilla
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
